channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - pymc = 5
  - plotly
  - matplotlib
  - scikit-learn
  - statsmodels
  - scipy
  - seaborn
  - anndata
  - streamlit